using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.Text;

namespace ModelPackages.Generators;

[Generator]
public sealed class ModelPackageGenerator : IIncrementalGenerator
{
    private const string ManifestFileName = "model-manifest.json";
    private const string DefaultClassName = "ModelPackageApi";
    private const string ClassNameProperty = "build_property.ModelPackageClassName";

    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        // Find model-manifest.json in AdditionalFiles
        var manifestFiles = context.AdditionalTextsProvider
            .Where(f => System.IO.Path.GetFileName(f.Path)
                .Equals(ManifestFileName, System.StringComparison.OrdinalIgnoreCase));

        // Get the custom class name from MSBuild property (if any)
        var classNameProvider = context.AnalyzerConfigOptionsProvider
            .Select((opts, _) =>
            {
                opts.GlobalOptions.TryGetValue(ClassNameProperty, out var name);
                return string.IsNullOrWhiteSpace(name) ? DefaultClassName : name!;
            });

        // Combine manifest content + class name + root namespace
        var combined = manifestFiles.Combine(classNameProvider)
            .Combine(context.AnalyzerConfigOptionsProvider.Select((opts, _) =>
            {
                opts.GlobalOptions.TryGetValue("build_property.RootNamespace", out var ns);
                return ns ?? "GeneratedModelPackage";
            }));

        context.RegisterSourceOutput(combined, (spc, pair) =>
        {
            var ((manifestText, className), rootNamespace) = pair;
            var content = manifestText.GetText(spc.CancellationToken)?.ToString();
            if (string.IsNullOrWhiteSpace(content))
            {
                spc.ReportDiagnostic(Diagnostic.Create(
                    Diagnostics.ManifestEmpty, Location.None, manifestText.Path));
                return;
            }

            var modelId = ManifestParser.ExtractModelId(content!);
            if (modelId == null)
            {
                spc.ReportDiagnostic(Diagnostic.Create(
                    Diagnostics.ManifestMalformed, Location.None, manifestText.Path));
                return;
            }

            var source = GenerateSource(rootNamespace, className, modelId);
            spc.AddSource($"{className}.g.cs", SourceText.From(source, Encoding.UTF8));
        });
    }

    private static string GenerateSource(string ns, string className, string modelId)
    {
        return $$"""
            // <auto-generated/>
            #nullable enable

            namespace {{ns}};

            /// <summary>
            /// Auto-generated model package wrapper for '{{modelId}}'.
            /// Extend this partial class to add inference-specific methods.
            /// </summary>
            public static partial class {{className}}
            {
                private static readonly global::System.Lazy<global::ModelPackages.ModelPackage> _package = new(() =>
                    global::ModelPackages.ModelPackage.FromManifestResource(typeof({{className}}).Assembly));

                /// <summary>Ensures the model is downloaded and cached. Returns the local file path.</summary>
                public static global::System.Threading.Tasks.Task<string> EnsureModelAsync(
                    global::ModelPackages.ModelOptions? options = null,
                    global::System.Threading.CancellationToken cancellationToken = default)
                    => _package.Value.EnsureModelAsync(options, cancellationToken);

                /// <summary>Ensures all model files are present locally.</summary>
                public static global::System.Threading.Tasks.Task<global::ModelPackages.ModelFiles> EnsureFilesAsync(
                    global::ModelPackages.ModelOptions? options = null,
                    global::System.Threading.CancellationToken cancellationToken = default)
                    => _package.Value.EnsureFilesAsync(options, cancellationToken);

                /// <summary>Returns model metadata without downloading.</summary>
                public static global::System.Threading.Tasks.Task<global::ModelPackages.ModelInfo> GetModelInfoAsync(
                    global::ModelPackages.ModelOptions? options = null,
                    global::System.Threading.CancellationToken cancellationToken = default)
                    => _package.Value.GetModelInfoAsync(options, cancellationToken);

                /// <summary>Verifies all cached model files' integrity.</summary>
                public static global::System.Threading.Tasks.Task VerifyModelAsync(
                    global::ModelPackages.ModelOptions? options = null,
                    global::System.Threading.CancellationToken cancellationToken = default)
                    => _package.Value.VerifyModelAsync(options, cancellationToken);

                /// <summary>Removes all cached model files.</summary>
                public static void ClearCache(
                    global::ModelPackages.ModelOptions? options = null)
                    => _package.Value.ClearCache(options);
            }
            """;
    }
}
